# Folder Structure Recommendation
# ~/terraform/
#     main.tf
#     variables.tf
#     outputs.tf
# ~/ansible/
#     inventory.ini      # Generated by script
#     configure.yml      # Playbook provided above
#     <keyname>.pem      # Copied from Terraform dynamically

#!/bin/bash

# ---------------------------
# Variables
# ---------------------------
TF_DIR="$HOME/terraform"           # Path where your Terraform files are
ANSIBLE_DIR="$HOME/ansible"        # Path to store inventory and playbooks
PLAYBOOK="$ANSIBLE_DIR/configure.yml"

# ---------------------------
# Step 1: Run Terraform
# ---------------------------
echo ">>> Initializing Terraform..."
cd $TF_DIR
terraform init

echo ">>> Applying Terraform configuration..."
terraform apply -auto-approve

echo ">>> Exporting Terraform outputs..."
terraform output -json instance_public_ips > instance_ips.json

# Get the key name dynamically from Terraform output
KEY_NAME=$(terraform output -raw key_name)   # Assumes you output key_name in Terraform
KEY_PATH="$ANSIBLE_DIR/$KEY_NAME"

# ---------------------------
# Step 2: Copy PEM file to Ansible directory
# ---------------------------
echo ">>> Copying PEM file to Ansible directory..."
cp "$TF_DIR/$KEY_NAME" "$KEY_PATH"
chmod 600 "$KEY_PATH"

# ---------------------------
# Step 3: Generate Ansible inventory
# ---------------------------
echo ">>> Generating Ansible inventory..."
mkdir -p $ANSIBLE_DIR
echo "[jenkins]" > $ANSIBLE_DIR/inventory.ini
echo "[docker_nginx]" >> $ANSIBLE_DIR/inventory.ini

for NAME in $(jq -r 'keys[]' instance_ips.json); do
  IP=$(jq -r --arg name "$NAME" '.[$name]' instance_ips.json)
  if [[ "$NAME" == *"jenkins"* ]]; then
    echo "$NAME ansible_host=$IP ansible_user=ec2-user ansible_ssh_private_key_file=$KEY_PATH" >> $ANSIBLE_DIR/inventory.ini
  else
    echo "$NAME ansible_host=$IP ansible_user=ec2-user ansible_ssh_private_key_file=$KEY_PATH" >> $ANSIBLE_DIR/inventory.ini
  fi
done

echo ">>> Inventory created at $ANSIBLE_DIR/inventory.ini"

# ---------------------------
# Step 4: Run Ansible Playbook
# ---------------------------
echo ">>> Running Ansible playbook..."
ansible-playbook -i $ANSIBLE_DIR/inventory.ini $PLAYBOOK
