#!/bin/bash

# ---------------------------
# Variables
# ---------------------------
TF_DIR="$HOME/terraform"           # Path where your main.tf and variables.tf are
ANSIBLE_DIR="$HOME/ansible"        # Path to store inventory and playbooks
KEY_NAME="ProgressPulse-key.pem"   # Key generated by Terraform
KEY_PATH="$ANSIBLE_DIR/$KEY_NAME"
INVENTORY_FILE="$ANSIBLE_DIR/inventory.ini"
PLAYBOOK="$ANSIBLE_DIR/configure.yml"

# ---------------------------
# Step 1: Run Terraform
# ---------------------------
echo ">>> Initializing Terraform..."
cd $TF_DIR
terraform init

echo ">>> Applying Terraform configuration..."
terraform apply -auto-approve

echo ">>> Exporting Terraform outputs..."
terraform output -json instance_public_ips > instance_ips.json

# ---------------------------
# Step 2: Copy PEM file to Ansible directory
# ---------------------------
echo ">>> Copying PEM file to Ansible directory..."
cp "$TF_DIR/$KEY_NAME" "$KEY_PATH"
chmod 600 "$KEY_PATH"

# ---------------------------
# Step 3: Generate Ansible inventory
# ---------------------------
echo ">>> Generating Ansible inventory..."
mkdir -p $ANSIBLE_DIR
echo "[all]" > $INVENTORY_FILE

for NAME in $(jq -r 'keys[]' instance_ips.json); do
  IP=$(jq -r --arg name "$NAME" '.[$name]' instance_ips.json)
  echo "$NAME ansible_host=$IP ansible_user=ec2-user ansible_ssh_private_key_file=$KEY_PATH" >> $INVENTORY_FILE
done

echo ">>> Inventory created at $INVENTORY_FILE"

# ---------------------------
# Step 4: Run Ansible Playbook
# ---------------------------
echo ">>> Running Ansible playbook..."
ansible-playbook -i $INVENTORY_FILE $PLAYBOOK
